services:
  postgres:
    platform: linux/amd64
    image: postgis/postgis:latest
    container_name: sample-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eatcloud_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./src/main/resources/DB/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./src/main/resources/DB/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro

  redis:
    image: redis:latest
    container_name: sample-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
